kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: pg-replication

nodes:
  - role: control-plane

  - role: worker
    labels:
      workload: postgres
      postgres-node: node-a

  - role: worker
    labels:
      workload: postgres
      postgres-node: node-b
