apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-config-${STUDENT_ID}
  namespace: pg-${STUDENT_ID}

data:
  postgresql.conf: |
    listen_addresses = '*'
    port = 5432
    
    wal_level = replica
    max_wal_senders = 10
    max_replication_slots = 10
    hot_standby = on

    wal_keep_size = 256MB
    password_encryption = scram-sha-256

  pg_hba.conf: |
    # TYPE       DATABASE        USER            ADDRESS                 METHOD

    # "local" is for Unix domain socket connections only (pod-local admin / health checks)
    local         all             all                                  scram-sha-256
    local         replication     all                                  scram-sha-256

    # IPv4 / IPv6 localhost
    host          all             all             127.0.0.1/32            trust
    host          all             all              ::1/128                trust

    # Allow replication connections from localhost, by a user with the replication privilege.
    host          replication     all             127.0.0.1/32            trust
    host          replication     all              ::1/128                trust

    # Pod network - app connections + streaming replication
    # (kind CNI is typically 10.244.0.0/16 but 0.0.0.0/0 is fine)
    host          all             all              0.0.0.0/0              trust
    host          replication     repl             0.0.0.0/0           scram-sha-256
