apiVersion: v1
kind: Secret
metadata:
  name: pg-creds-${STUDENT_ID}
  namespace: pg-${STUDENT_ID}

type: Opaque

stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  REPLICATION_USER: repl
  REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
